# Generated by Django 5.1 on 2024-09-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hero_name', models.CharField(max_length=100)),
                ('Heroine_name', models.CharField(max_length=100)),
                ('Director_name', models.CharField(max_length=100)),
                ('Producer_name', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
